name: mobile_dudu_pro
description: "DUDU Pro - Application pour les chauffeurs"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  http: ^1.5.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  socket_io_client: ^3.1.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
